### ISSUE TITLE
cd -

### ISSUE THREAD

**Issue by Gammerdinger** [hbctraining/Intro-to-shell-flipped#19]
We have discussed adding cd - to perhaps the Day 1 shortcuts, but we weren't exactly sure where we liked it. Separately, but related we discussed the $OLDPWD internal variable in bash that cd - uses and you can echo, but I am not sure sure what to do with that. I think we could teach cd - without $OLDPWD, but its sort of nice flavor to know about that variable too.

**Comment by hwick** [comment]
I added  this as a tip at the end of the discussion about full vs relative paths. This seemed like a good place to put it because it can save people time navigating back and forth without having to type a lot. I did mention that it references $OLDPWD, but "we will learn more about variables later" -- can be removed if it's too much
